version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "08:00"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@typescript-eslint/eslint-plugin"
        versions: ["6.x"]
      - dependency-name: "@typescript-eslint/parser"
        versions: ["6.x"]
      - dependency-name: "eslint"
        versions: ["8.x"]