version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "08:00"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "@types/vscode"
        versions: ["1.85.0"]