name: 'Application analysis'
on: push

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps: 
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup node 
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            
        - name: Run install
          uses: borales/actions-yarn@v4
          with:
            cmd: install

        # - name: compile aplication
        #   run: yarn compile

        - name: lint
          run: yarn lint

        - name: Save coverage report
          uses: actions/upload-artifact@v3
          with:
            name: coverage-report
            path: coverage
            retention-days: 1

        - name: coverage
          uses: ArtiomTr/jest-coverage-report-action@v2
          with: 
            package-manager: yarn
            test-script: yarn jest --coverage --silent --json --outputFile=report.json
            # coverage-file: report.json
            coverage-file: ./coverage/report.json
            base-coverage-file: ./coverage/report.json # this line added
            skip-step: all