name: 'Application analysis'
on: push

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps: 
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup node 
          uses: actions/setup-node@v4
          with:
            node-version: latest
            
        - name: Run install
          uses: borales/actions-yarn@v4
          with:
            cmd: install

        - name: compile aplication
          run: yarn compile

        - name: lint
          run: yarn lint

        - name: coverage
          uses: ArtiomTr/jest-coverage-report-action@v2
          env:
            NODE_OPTIONS: '--max_old_space_size=4096'
          with:
            test-script: yarn jest --coverage --silent --json --outputFile=report.json
            coverage-file: ../../report.json