name: 'Application analysis'
on: push

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps: 
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup node 
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            
        - name: Run install
          uses: borales/actions-yarn@v4
          with:
            cmd: install

        - name: compile aplication
          run: yarn compile

        - name: lint
          run: yarn lint

        - name: test
          run: yarn coverage