name: 'Report coverage tests'
on: push

jobs:
    build: 
      uses: ./.github/workflows/build.yaml

    lint:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node 
              uses: actions/setup-node@v3
              with: 
                node-version: 18.18.x
            
            - name: Run install
              uses: borales/actions-yarn@v4
              with:
                cmd: install

            - name: Lint
              run:  yarn lint

    test-coverage:
        needs: lint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node 
              uses: actions/setup-node@v3
              with: 
                node-version: 18.18.x
            
            - name: Run install
              uses: borales/actions-yarn@v4
              with:
                cmd: install

            - name: Generated report coverage
              run:  yarn coverage