name: 'Report coverage tests'
on: push

jobs:
    build: 
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node 
              uses: actions/setup-node@v3
              with: 
                node-version: 18.18.x
            
            - name: Run install
              uses: borales/actions-yarn@v4

            - name: Install packages
              run: pnpm install

            - name: compile aplication
              run: pnpm compile

    lint:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node 
              uses: actions/setup-node@v3
              with: 
                node-version: 18.18.x
            
            - name: Run install
              uses: borales/actions-yarn@v4

            - name: Install packages
              run: pnpm install

            - name: Lint
              run:  pnpm lint

    test-coverage:
        needs: lint
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node 
              uses: actions/setup-node@v3
              with: 
                node-version: 18.18.x
            
            - name: Run install
              uses: borales/actions-yarn@v4

            - name: Install packages
              run: pnpm install

            - name: Generated report coverage
              run:  pnpm coverage