# name: 'Report coverage tests'
# on: push

# jobs:
#     build: 
#       uses: ./.github/workflows/build.yaml

#     lint:
#         needs: build
#         runs-on: ubuntu-latest

#         steps:
#             - name: build
#               uses: ./.github/workflows/build.yaml

#             - name: Lint
#               run:  yarn lint

#     test-coverage:
#         needs: lint
#         runs-on: ubuntu-latest

#         steps:
#             - name: build
#               uses: ./.github/workflows/build.yaml

#             - name: Generated report coverage
#               run:  yarn coverage


name: 'coverage'
# on:
#   pull_request:
#     branches:
#       - master

on: push

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/workflows/build.yaml
            - uses: ArtiomTr/jest-coverage-report-action@v2